app/__init__.py
from flask import Flask
from flask_ngrok import run_with_ngrok

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)
    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera
from source.test_new_images import detect_cig_in_image
from source.video_detector import detect_cig_in_frame
from flask import Flask, jsonify
import os

cig_or_not ='No Smoking'
confidence = 100
@main_bp.route("/")
def home_page():
    return render_template("home_page.html")

@main_bp.route("/data")
def data():
    global cig_or_not
    global confidence
    return jsonify(cig_or_not=cig_or_not,confidence=confidence)

@main_bp.route("/penjelasan_model")
def penjelasan_model():
    return render_template("penjelasan_model.html")

@main_bp.route("/pengujian")
def pengujian():
    return render_template("pengujian.html")


def gen(camera):
    global cig_or_not
    global confidence
    while True:
        frame = camera.get_frame()
        frame_processed,cig_or_not,confidence = detect_cig_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-cig-detector", methods=["GET", "POST"])
def image_cig_detector():
    return render_template("image_detector.html",form = PhotoCigForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoCigForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_cig_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img
        
@main_bp.route("/about")
def about():
    return render_template("about.html")

# form
class PhotoCigForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png', 'jfif'], 'The allowed extensions are: .jpg, .jpeg, .jfif and .png')])

    submit = SubmitField('Detect')

app/templates/about.html
{% extends "template.html" %}
{% block content %}
<section class="py-5" id="about">
    <div class="container pr-0">
        <div class="row">
            <div class="col-md-6 mx-auto text-center pt-6">
                <h2>Penjelasan Aplikasi</h2>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-11 mx-auto">
                <div class="col text-justify">
                    <div class="col-md-12">
                        <h4>Abstrak</h4>
                        <p class="text-black"> Rokok mengandung zat berbahaya yang dapat menyebabkan ketagihan dan
                            berbagai penyakit bahkan hingga menyebabkan kematian. Dampak buruk tersebut tidak hanya
                            dirasakan oleh perokok tetapi juga bisa dirasakan oleh masyarakat lainnya saat melakukan
                            aktivitas pola hidup sehat terutama di kawasan tanpa asap rokok. Dengan demikian penelitian
                            ini untuk membangun model penerapan deep learning pada klasifikasi citra untuk mendeteksi
                            orang merokok dan tidak merokok, berbasis website agar dapat digunakan untuk melakukan
                            monitoring pada kawasan tanpa asap rokok.</p>
                        <p class="text-black"> Dalam penelitian ini, metode yang digunakan adalah Convolutional Neural
                            Network dengan arsitektur MobileNetV2. Dataset yang digunakan berupa gambar orang merokok
                            dan tidak merokok. Sebelum data di proses akan dilakukan preprocessing data yaitu berupa
                            augmentasi data, pemodelan dan implementasi. </p>
                        <p class="text-black"> Penelitian ini mengusulkan sebuah aplikasi website menggunakan bahasa
                            pemrograman Python dengan framework flask. Aplikasi yang dibangun memiliki fitur yang
                            menampilkan tentang penelitian, penjelasan model, dataset, dan testing dengan menggunakan
                            real time webcam atau input file. Hasil dari pengujian menunjukkan nilai akurasi 92.45%,
                            presisi sebesar 95.83%, dan recall sebesar 88.46%. </p>
                    </div>
                    <div class="col-md-12 pt-3">
                        <h4>Abstract</h4>
                        <p class="text-black font-italic">Cigarettes contain harmful substances that can cause addiction
                            and various diseases and even cause death. This bad impact is not only felt by active
                            smokers, but this can also interfere with other people when carrying out healthy lifestyle
                            activities, especially in areas without smoking. Therefore, this is the basic motivation for
                            this research to build a model for implementing deep learning in image classification to
                            detect smoking and non-smoking people, based on a website so that it can be used to monitor
                            smoke-free areas.</p>
                        <p class="text-black font-italic">In this study, the method used is the Convolutional Neural
                            Network with the MobileNetV2 architecture. The dataset used in this study is in the form of
                            smoking and non-smoking images. The next stage is the preprocessing stage in the form of
                            data augmentation, modeling, and implementation.</p>
                        <p class="text-black font-italic">This research was applied to a website using the Python
                            programming language with the flask framework. The application that is built has features
                            that display research, explanation of models, datasets, and testing using real time webcams
                            or input files. The results of the test show an accuracy of 92.45%, a precision of 95.83%,
                            and a recall of 88.46%.</p>
                    </div>
                    <div class=" row ">
                        <div class="col-md-3 pt-5 ">
                            <div class="image-profil">
                                <img class="img-fluid"
                                    src="../static/images/WhatsApp Image 2022-05-12 at 21.13.50.jpeg" />
                            </div>
                        </div>
                        <div class="col-md-5 pt-5">
                            <h3 class="fw-bonlder" style="font-weight: 550">Penulis & Perancang Aplikasi</h3>
                            <h5 class="text-black" style="font-weight: 500">Hadiza Cahya Firdaus</h5>
                            <p class="text-black" style="font-weight: 400">NPM : 140810180042</p>
                        </div>
                        <div class="col-md-4 mb-5 pt-5">
                            <h3 class="fw-bolder" style="font-weight: 550">Pembimbing Penelitian</h3>
                            <h5 class="text-black" style="font-weight: 420">Dr. Afrida Helen, M.Kom</h5>
                            <p class="text-black" style="font-weight: 400">NIP : 19650128 199703 2 001</p>
                            </br>
                            <h3 class="fw-bolder" style="font-weight: 550">Co-Pembimbing Penelitian</h3>
                            <h5 class="text-black" style="font-weight: 420">Akmal, S.Si., MT</h5>
                            <p class="text-black" style="font-weight: 400">NIP : 19700615 199803 1 993 </p>
                        </div>
                        <div class="col-md-12 mb-5">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}
{% block content %}
<section class="py-7 py-md-0 bg-hero" id="home">
    <div class="container">
        <div class="row vh-md-100">
            <div class="col-md-8 col-sm-10 col-12  mx-auto my-auto text-center">
                <h1 class="heading-black text-capitalize" style="color: #000;">CIGITION</h1>
                <p class="lead py-3">Cigarette Identification merupakan website yang digunakan untuk mendeteksi
                    aktivitas
                    seseorang yang sedang merokok atau tidak dengan Artificial Intelligence yaitu model Convolutional
                    Neural Network.
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}

<div class="container">
    <div class="container-fluid" style="background-color: whitesmoke;">
        <div id="frame_container" class="row py-5 pt-5 mt-5">
            <div class="col-12 pt-5 mt-5">
                <img src="/static/images/maxresdefault.jpg" id="image-preview" style="max-width:400px"
                    class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    var previewImage = function (event) {
        var element_id = "image-preview";
        var preview = document.getElementById(element_id);
        preview.src = URL.createObjectURL(event.target.files[0]);
        preview.style.display = "block";
        $("#submit").prop("disabled", false);
    };
    $(document).ready(function () {
        $('#live').attr('class', 'nav-item');
        $('#image-detector').attr('class', 'nav-item active');
    })
    $(function () {
        $("#submit").each(function (index) {
            $(this).on('click', function (e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
                $('#image-form').serializeArray().forEach(
                    function (item, index) {
                        formData.append(item.name, item.value);
                    }
                );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url: url + '',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith(
                            '<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>'
                        );
                        $("#form-row").remove();
                    },
                    error: function (response) {
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>

{% endblock %}

app/templates/pengujian.html
{% extends "template.html" %}
{% block content %}
<section class="pt-6 pb-7" id="features">
    <div class="container">
        <div class="container-fluid" style="background-color:whitesmoke">
            <div id="frame_container" class="row">
                <div class="col-12">
                    <div>
                        <img src="/static/images/turn-on.png" class="img-thumbnail img-fluid mx-auto d-block"
                            style="background-color:whitesmoke">
                    </div>
                    <div class="titleDetections">
                        <h1 id="cig_or_not"></h1>
                    </div>
                </div>
            </div>
            <div class="row mt-3 mb-5">
                <div class="col-6 d-flex justify-content-end">
                    <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                            aria-hidden="true"></i> Start
                    </button>
                </div>
                <div class="col-6 d-flex justify-content-start">
                    <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                            aria-hidden="true"></i> Stop
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function () {
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
    })

    function stop() {
        $("img").attr("src", "/static/images/SL4578.png");
        $("#stop").attr("class", "btn btn-danger active");
        $("#cig_or_not").attr("class", "d-none");

        $("#start").attr("class", "btn btn-outline-success");
    }

    function start() {
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class", "btn btn-success active");
        $("#cig_or_not").attr("class", "d-flex");

        $("#stop").attr("class", "btn btn-outline-danger");

        var $SCRIPT_ROOT = 'http://DESKTOP-BC8D30A:8080'
        var intervalID = setInterval(update_values, 1000);

        function update_values() {
            $.getJSON($SCRIPT_ROOT + '/data',

                function (data) {
                    $('#cig_or_not').text(data.cig_or_not)
                    // $('#confidence').text(data.confidence)
                });

        };
    }
</script>

{% endblock %}

app/templates/penjelasan_model.html
{% extends "template.html" %}
{% block content %}

<section class="py-7" id="faq">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2>Penjelasan Model</h2>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-12 mx-auto">
                <div class="row">
                    <div class="col-md-12 mb-5">
                        <h6>Dataset</h6>
                        <p class="text-black">Data yang digunakan dalam penelitian ini berupa data gambar yang merupakan
                            foto sejumlah orang dengan dua kondisi, kondisi pertama diterapkan pada penelitian ini yaitu
                            kondisi orang yang sedang melakukan aktivitas merokok dan kondisi orang yang sedang tidak
                            merokok. </p>
                        <p class="text-black"> Dataset yang dikumpulkan dari penelitian ini beberapa diambil secara
                            mandiri dan diambil juga dari website Kaggle yang dapat akses <a class="fw-bolder"
                                href="https://www.kaggle.com/datasets/raj713335/cigrarette-data">disini.</a></p>
                    </div>
                    <div class="col-md-12 mb-5">
                        <h6>Hasil Training Model</h6>
                        <div class="col-12">
                            <img src="../static/images/epooch.png" class="img-thumbnail img-fluid mx-auto d-block">
                            <p class="text-black mt-5">Accuracy : parameter uji yang menentukan kelayakan dari sebuah
                                sistem dalam mengklasifikasikan pendeteksi aktivitas merokok</p>
                            <p class="text-black">Loss : parameter uji yang digunakan untuk menghitung data yang tidak
                                terdeteksi (loss) saat proses pelatihan maupun pengujian</p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function () {
        $('#image-detector').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
    })

    function stop() {
        $("img").attr("src", "/static/images/stay-safe.jpg");
        $("#stop").attr("class", "btn btn-danger active");

        $("#start").attr("class", "btn btn-outline-success");
    }

    function start() {
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class", "btn btn-success active");

        $("#stop").attr("class", "btn btn-outline-danger");
    }
</script>

{% endblock %}

app/templates/template.html
<!doctype html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CIGITION</title>
    <meta name="description" content="Knight is a beautiful Bootstrap 4 template for product landing pages." />

    <!--Inter UI font-->
    <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

    <!--vendors styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    <!-- Bootstrap CSS / Color Scheme -->
    <link rel="stylesheet" href="static/css/main.css">
    <link rel="stylesheet" href="static/css/style.css">
</head>

<body>
    <div class="wrapper">
        <section class="smart-scroll">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md">
                    <a class="navbar-brand heading-black" href="/">
                        CIGITION
                    </a>
                    <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span data-feather="grid"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link page-scroll" href="/">Homepage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link page-scroll" href="/penjelasan_model">Model</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link page-scroll" href="/about">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link page-scroll" href="/pengujian">Testing Real Time</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link page-scroll" href="/image-cig-detector">Testing Image</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </section>

        <div class="content">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            {{ message }}
            {% endfor %}
            {% endif %}
            {% endwith %}

            <!--add custom content with inheritance-->
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- jQuery, Popper.js, and Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script src="static/js/scripts.js"></script>
</body>
{% block custom_js %}
{% endblock %}
</body>

</html>